# Generated by Django 6.0 on 2026-01-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
