# Generated by Django 6.0 on 2026-01-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supabase', '0002_comments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
