# Generated by Django 6.0 on 2026-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Genero', models.TextField()),
                ('Edad', models.IntegerField()),
                ('Universo', models.TextField()),
            ],
        ),
    ]
