# Generated by Django 6.0 on 2026-01-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_personajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personajes',
            new_name='Personaje',
        ),
    ]
